"""leaderboard table, and fetching data from user table

Revision ID: 01abe4e2531f
Revises: ff90dbb39796
Create Date: 2025-03-13 03:02:50.556414

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '01abe4e2531f'
down_revision = 'ff90dbb39796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaderboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('virtual_balance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('bhav_copy', schema=None) as batch_op:
        batch_op.alter_column('prev_close',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('open_price',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('high',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('low',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('last_price',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('close_price',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('avg_price',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('volume',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('turnover_lacs',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('no_of_trades',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('deliv_qty',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('deliv_per',
               existing_type=mysql.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bhav_copy', schema=None) as batch_op:
        batch_op.alter_column('deliv_per',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('deliv_qty',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('no_of_trades',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('turnover_lacs',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('volume',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('avg_price',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('close_price',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('last_price',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('low',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('high',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('open_price',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('prev_close',
               existing_type=mysql.FLOAT(),
               nullable=True)

    op.drop_table('leaderboard')
    # ### end Alembic commands ###
